My_ToDo/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("", include("ToDo.urls")),
    path('admin/', admin.site.urls),
]

ToDo/urls.py
from django.urls import path

from .import views


app_name = "ToDo"
urlpatterns = [
    path("", views.index, name="index"),
    path("edit/<int:task_id>", views.edit_task, name="edit_task"),
    path("delete/<int:task_id>", views.delete_task, name="delete_task"),
]

ToDo/models.py
from django.db import models

class Task(models.Model):
    todo_task = models.CharField(max_length=5000)

    def __str__(self):
        return self.todo_task

ToDo/forms.py
from django import forms
from .models import Task


class TaskForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = ["todo_task"]
        widgets = {
            'todo_task': forms.TextInput(attrs={'class': 'input is-primary', 'placeholder': 'Enter Todo'}),
        }

ToDo/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Task
from .forms import TaskForm

def index(request):
    tasks = Task.objects.all()
    form = TaskForm()
    if request.method == "POST":
        form = TaskForm(request.POST)
        if form.is_valid:
            form.save()
            return redirect('ToDo:index')
    return render(request, "ToDo/index.html", {"tasks": tasks, "form": form})

def edit_task(request, task_id):
    task = get_object_or_404(Task, id=task_id)
    if request.method == "POST":
        form = TaskForm(request.POST, instance=task)
        if form.is_valid():
            form.save()
            return redirect('ToDo:index')
    else:
        form = TaskForm(instance=task)
    return render(request, "ToDo/edit_task.html", {'form': form})

def delete_task(request, task_id):
    task = get_object_or_404(Task, id=task_id)
    if request.method == "POST":
        task.delete()
        return redirect('ToDo:index')

ToDo/templates/ToDo/edit_task.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Edit Task</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@1.0.0/css/bulma.min.css">
</head>
<body>
    <section class="section">
        <div class="container">
            <h1 class="title">Edit Task</h1>
            <form method="post">
                {% csrf_token %}
                {% for field in form %}
                    <div class="field">
                        <!-- <label class="label">{{ field.label }}</label> -->
                        <div class="control">
                            <input class="input is-primary" type="text" name="todo_task" value="{{ form.instance.todo_task }}">
                        </div>
                    </div>
                {% endfor %}
                <button type="submit" class="button is-info">Save</button>
            </form>
        </div>
    </section>
</body>
</html>

ToDo/templates/ToDo/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>ToDo App</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@1.0.0/css/bulma.min.css">
    <style>
        .scrollable-content {
            max-height: 400px;
            overflow-y: auto;
        }
        label {
            display: none;
        }
    </style>
</head>
<body>
    <section class="section">
        <div class="container is-max-desktop">
            <div class="box">
                <h1 class="title">ToDo App</h1>
                <form method="post">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button class = "button is-info" type="submit">Add</button>
                </form>
               
            </div>
        </div> 
    </section>

    <section class="section">
        <div class="container is-max-desktop">
            <div class="box scrollable-content">
                {% for task in tasks %}
                    <article class="message is-info">
                        <div class="message-header">
                            <div class="level is-mobile" style="width: 100%; align-items: center;">
                                <div class="level-left" style="flex-grow: 1; overflow: hidden;">
                                    <p style="white-space: nowrap; overflow: hidden; text-overflow: ellipsis;">
                                        {{ task }}
                                    </p> 
                                </div>
                                <div class="level-right">
                                    <form action="{% url 'ToDo:edit_task' task.id %}" method="post" class="level-item" style="margin-right: 5px;"> 
                                        {% csrf_token %} 
                                        <button type="submit" class="button is-warning is-small">Edit</button>
                                    </form>
                                    <form id="edit-form-{{ task.id }}" action="{% url 'ToDo:delete_task' task.id %}" method="post"> 
                                        {% csrf_token %}
                                        <button type="submit" class="button is-warning is-small">Delete</button>
                                    </form>
                                </div>
                                 
                            </div>
                            
                        </div>
                    </article>
                {% endfor %}       
            </div>
        </div>
    </section>
</body>
</html>